mutation CreateMovieList @auth(level: USER) {
  movieList_insert(data: {
    name: "My New List",
    description: "A list of my favorite movies",
    isPublic: false,
    userId_expr: "auth.uid",
    updatedAt_expr: "request.time",
    createdAt_expr: "request.time"
  })
}

query GetPublicMovieLists @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  movieLists(where: {isPublic: {eq: true}}) {
    id
    name
    description
  }
}

mutation AddMovieToList($movieListId: UUID!, $movieId: UUID!, $position: Int!) @auth(level: USER) {
  movieListEntry_insert(data: {
    movieListId: $movieListId,
    movieId: $movieId,
    position: $position
  })
}

query GetMoviesInList($movieListId: UUID!) @auth(level: USER) {
  movieList(id: $movieListId) {
    movieListEntries_on_movieList {
      movie {
        id
        title
        year
      }
      position
    }
  }
}